# Generated by Django 2.1.3 on 2018-12-02 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='attended',
            field=models.BooleanField(default=False),
        ),
    ]
