# Generated by Django 2.1.3 on 2018-11-25 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='proce',
            new_name='price',
        ),
    ]
