# Generated by Django 2.1.3 on 2018-11-25 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20181124_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='tittle',
            new_name='title',
        ),
    ]
